name: flutter_video_app
description: a play anime app
version: 0.6.6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 本地化
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:

  cupertino_icons: ^0.1.2
  rxdart:
  built_value:
  built_collection:
  url_launcher:
  mobx:
  flutter_mobx:
  html:
  webview_flutter:
  moor_flutter:
  package_info:

  # 在通知用户时需要更多自定义的snackbar
  flushbar:

  # apk升级策略
  flutter_github_releases_service: ^0.4.2

  # 可滑动列表项
  flutter_slidable: ^0.5.4

  # 底部泡泡栏
  bubble_bottom_bar: ^1.2.0

  video_box: ^0.10.1
  flutter_ajanuw_router: ^0.3.3
  get_it: ^3.0.3
  toast:
  breakpoints: ^0.2.0
  ajanuw_http:

  flutter_screen:
    git:
      url: https://github.com/januwA/flutter_screen
      ref: master

  flutter_android_pip:
    git:
      url: https://github.com/januwA/flutter_android_pip
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator:
  mobx_codegen:
  moor_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/images/drawer_header.jpg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
