name: flutter_video_app
description: a play anime app
version: 0.5.19

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 本地化
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:

  cupertino_icons: ^0.1.2
  rxdart: ^0.22.2
  built_value: ^6.7.1
  built_collection: ^4.2.2

  # 打开浏览器
  url_launcher: ^5.2.2
  mobx: ^0.3.8+1
  flutter_mobx: ^0.3.3+1

  # 视频播放器
  video_box: ^0.7.2

  # 解析html字符串
  html: ^0.14.0+2

  # webview
  webview_flutter: ^0.3.14+1

  # sqlite
  moor_flutter: ^1.7.0

  # 在通知用户时需要更多自定义的snackbar
  flushbar: ^1.9.1

  # apk升级策略
  flutter_github_releases_service: ^0.4.0

  # 可滑动列表项
  flutter_slidable: ^0.5.3

  # 底部泡泡栏
  bubble_bottom_bar: ^1.2.0
  flutter_ajanuw_router: ^0.2.2
  get_it:
  http_interceptor:
    git:
      url: https://github.com/januwA/http_interceptor.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  built_value_generator: ^6.7.1
  mobx_codegen:
  moor_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/images/drawer_header.jpg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
