name: flutter_video_app
description: a play anime app
version: 0.4.5

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  rxdart: ^0.22.0
  built_value:
  built_collection:
  url_launcher: ^5.0.3
  mobx:
  flutter_mobx:
  provider:
  video_box: ^0.3.0
  html: ^0.14.0+1
  webview_flutter:
  package_info: ^0.4.0+5
  path_provider: ^1.1.0
  path:
  moor_flutter:
  flushbar:
  flutter_github_releases_service:
  flutter_slidable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator:
  mobx_codegen:
  moor_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/images/drawer_header.jpg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
