name: flutter_video_app
description: a play anime app
version: 0.6.3

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 本地化
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:

  cupertino_icons: ^0.1.2
  rxdart: ^0.23.1
  built_value:
  built_collection:
  url_launcher:
  mobx:
  flutter_mobx:
  html:
  webview_flutter:
  moor_flutter:
  package_info:

  # 在通知用户时需要更多自定义的snackbar
  flushbar: ^1.9.1

  # apk升级策略
  flutter_github_releases_service: ^0.4.2

  # 可滑动列表项
  flutter_slidable: ^0.5.4

  # 底部泡泡栏
  bubble_bottom_bar: ^1.2.0
  
  video_box: ^0.9.1
  flutter_ajanuw_router: ^0.3.1
  get_it: ^3.0.3
  http_interceptor:
    git:
      url: https://github.com/januwA/http_interceptor.git
      ref: master
  
  toast: ^0.1.5
  breakpoints: ^0.2.0
  screen:
  flutter_android_pip:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator:
  mobx_codegen:
  moor_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/images/drawer_header.jpg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
